# Generated by Django 4.0.5 on 2022-06-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compositions',
            new_name='Composition',
        ),
    ]
