# Generated by Django 4.0.4 on 2022-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0002_rename_compositions_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='chord1_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='chord2_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='chord3_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='chord4_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='chord5_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord1',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord2',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord3',
            field=models.CharField(choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], max_length=5),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord4',
            field=models.CharField(choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], max_length=5),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord5',
            field=models.CharField(choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], max_length=5),
        ),
    ]
