# Generated by Django 4.0.4 on 2022-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0004_rename_chord1_composition_chord1_tonic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord1_style', models.CharField(blank=True, choices=[('arpup', 'upwardarpeggios')], default=None, max_length=50, null=True)),
                ('chord1_denom', models.IntegerField()),
                ('chord2_style', models.CharField(blank=True, choices=[('arpup', 'upwardarpeggios')], default=None, max_length=50, null=True)),
                ('chord2_denom', models.IntegerField()),
                ('chord3_style', models.CharField(blank=True, choices=[('arpup', 'upwardarpeggios')], default=None, max_length=50, null=True)),
                ('chord3_denom', models.IntegerField()),
                ('chord4_style', models.CharField(blank=True, choices=[('arpup', 'upwardarpeggios')], default=None, max_length=50, null=True)),
                ('chord4_denom', models.IntegerField()),
                ('chord5_style', models.CharField(blank=True, choices=[('arpup', 'upwardarpeggios')], default=None, max_length=50, null=True)),
                ('chord5_denom', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord3_tonic',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], default=None, max_length=5, null=True),
        ),
    ]
