# Generated by Django 4.0.4 on 2022-06-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0005_track_alter_composition_chord3_tonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='comp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='userinput.composition'),
        ),
        migrations.AddField(
            model_name='track',
            name='trackname',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
