# Generated by Django 4.0.4 on 2022-06-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0006_track_comp_track_trackname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='chord1_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord2_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord3_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord4_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord4_tonic',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord5_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord5_tonic',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A#', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#', 'C#/Db'), ('D', 'D'), ('D#', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/Gb'), ('G', 'G'), ('G#', 'G#/Ab')], default=None, max_length=5, null=True),
        ),
    ]
