# Generated by Django 4.0.4 on 2022-06-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0008_alter_track_chord1_denom_alter_track_chord2_denom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='chord1_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default='major', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord2_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default='major', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord3_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default='major', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord4_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default='major', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord5_quality',
            field=models.CharField(blank=True, choices=[('', ''), ('major', 'major'), ('minor', 'minor')], default='major', max_length=10, null=True),
        ),
    ]
