# Generated by Django 4.0.4 on 2022-06-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0009_alter_composition_chord1_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='chord1_style',
            field=models.CharField(blank=True, choices=[('arpup', 'upward arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord2_style',
            field=models.CharField(blank=True, choices=[('arpup', 'upward arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord3_style',
            field=models.CharField(blank=True, choices=[('arpup', 'upward arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord4_style',
            field=models.CharField(blank=True, choices=[('arpup', 'upward arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord5_style',
            field=models.CharField(blank=True, choices=[('arpup', 'upward arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
    ]
