# Generated by Django 4.0.4 on 2022-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0013_alter_composition_chord1_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='sequence1_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='sequence2_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='sequence3_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='sequence4_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='sequence5_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
