# Generated by Django 4.0.4 on 2022-06-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0014_composition_sequence1_mutators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='sequence1_mutators',
            new_name='chord1_mutators',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='sequence2_mutators',
            new_name='chord2_mutators',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='sequence3_mutators',
            new_name='chord3_mutators',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='sequence4_mutators',
            new_name='chord4_mutators',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='sequence5_mutators',
            new_name='chord5_mutators',
        ),
    ]
