# Generated by Django 4.0.4 on 2022-06-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0015_rename_sequence1_mutators_composition_chord1_mutators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='chord1_mutators',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='chord2_mutators',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='chord3_mutators',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='chord4_mutators',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='chord5_mutators',
        ),
        migrations.AddField(
            model_name='track',
            name='chord1_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='chord2_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='chord3_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='chord4_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='chord5_mutators',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
