# Generated by Django 4.0.4 on 2022-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0016_remove_composition_chord1_mutators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='chord1_bars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord2_bars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord3_bars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord4_bars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='chord5_bars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord1_style',
            field=models.CharField(blank=True, choices=[('arpup', 'arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord2_style',
            field=models.CharField(blank=True, choices=[('arpup', 'arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord3_style',
            field=models.CharField(blank=True, choices=[('arpup', 'arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord4_style',
            field=models.CharField(blank=True, choices=[('arpup', 'arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='chord5_style',
            field=models.CharField(blank=True, choices=[('arpup', 'arpeggios'), ('simpline', 'steady bass')], default=None, max_length=50, null=True),
        ),
    ]
